version: '3.4'

services:
  db:
   image: mcr.microsoft.com/mssql/server:2019-latest
   ports:
    - 1433:1433
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
  ui:
   image: ${DOCKER_REGISTRY-}kindnessui
   build:
    context: .
    dockerfile: kindnessui/Dockerfile